ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'
 
Vagrant.configure("2") do |config|
 
  config.vm.synced_folder ".", "/var/shared"
 
  config.vm.define "lpebase" do |a|
    a.vm.provider "docker" do |d|
      d.build_dir = "."
      d.build_args = ["-t=lpebase"]
      d.ports = ["3000:3000"]
      d.name = "lpebase"
      d.remains_running = true
      d.cmd = ["whoami"]
    end
  end
 
end

