# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/home/lperez/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git git-flow gitignore jira git-extras mvn gradle sudo)

source $ZSH/oh-my-zsh.sh

# User configuration
source "$HOME/.sdkman/bin/sdkman-init.sh"

HISTFILE=~/.histfile
HISTSIZE=100000
SAVEHIST=100000
bindkey -e
bindkey ^f  history-incremental-search-backward

  case $TERM in
  (xterm*)
        function precmd () { print -Pn "\e]0;%n($(id -ng))@%m:%~\a" }
  ;;
  esac

zstyle :compinstall filename '/Users/lperez/.zshrc'

autoload -Uz compinit
compinit
autoload promptinit
promptinit
prompt clint
setopt correctall
setopt autocd
setopt auto_cd
setopt auto_pushd
setopt pushd_ignore_dups
setopt pushd_silent

# export MANPATH="/usr/local/man:$MANPATH"
export ANDROID_SDK_ROOT="/home/lperez/Android/Sdk"
export ANDROID_HOME="/home/lperez/Android/Sdk"
export PATH="${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools"
export JDK_HOME=$JAVA_HOME
export M2_HOME='/home/lperez/Bureau/work/apache-maven-3.6.3'
export PATH=$PATH:$M2_HOME/bin
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

alias wk='~/Bureau/work'
alias plz='sudo'
alias fl='~/Bureau/work/farmlife'
alias tsp='/home/lperez/Téléchargements/TeamSpeak3-Client-linux_amd64/ts3client_runscript.sh'
alias ggit='~/Bureau/work/farmlife'
alias grostas='sudo du -a /data | sort -n -r | head -n 10'
git config --global rebase.autosquash true
git config --global rerere.enabled true
git config --global pull.rebase merges
git config --global remote.origin.prune true
git config --global alias.dog "log --all --decorate --oneline --graph"
git config --global alias.merge "merge -Xignore-all-space"
git config --global alias.tidy "rebase -i @{upstream}"
git config --global alias.st status
git config --global alias.com commit
git config --global alias.ci commit
git config --global alias.br branch
git config --global alias.co checkout
git config --global alias.cl checkout
git config --global alias.superlog "log -p -M --follow --stat --"
alias glog='git lg1'
alias gk='gitk'
alias pull='git pull'
alias dev='git checkout dev'
alias lop='git checkout dev'
alias gwl='git worktree list'
alias gba='git branch -avv'
alias gco='git checkout'
alias gmm='git merge master'
alias gdo='git diff origin/master'
alias gdp='git diff @{push}..'
alias glp='git log @{push}..'
alias gpdo='git diff origin/master'
alias grso='git remote show origin'
alias co='git checkout'
alias grh='git reset --hard HEAD^'
alias itg='git co integration'
alias master='git co master'
alias ms='git checkout master'
alias mcc='mvn clean compile'
alias grc='gradle clean compile'
alias grct='gradle clean test'
alias grt='gradle test'
alias mcp='mvn clean package'
alias mci='mvn clean install'
alias mcu='mvn clean install -U'
alias mcd='mvn clean install deploy -U'
alias CLEARREPO='rm -fr ~/.m2/repository'
alias repoclear='rm -fr ~/.m2/repository'
alias ll='ls -la'
alias grep='egrep --exclude-dir=\.svn --color=auto'
alias s='cd ..'
alias c='clear'
alias ll='ls -la'
alias rtl='ls -rtla'
alias less='less --quiet'
alias '..'='cd ..'
alias -g ...='../..'
alias -g ....='../../..'
alias -g .....='../../../..'
alias svndiff='svn diff --diff-cmd ~/.diffwrap.sh'
alias sd='svn diff --diff-cmd=colordiff'
alias ant='ant -logger org.apache.tools.ant.listener.AnsiColorLogger'
alias dps='docker ps'
alias db='docker exec -it container /bin/bash'
alias ddown='docker-compose down -v'
alias dstop='docker-compose stop'
# servers
alias tbbweb1='ssh tbbweb1'
alias bbweb1='ssh bbweb1'


# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
