# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=/Users/lperez/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Set list of themes to load
# Setting this variable when ZSH_THEME=random
# cause zsh load theme from this variable instead of
# looking in ~/.oh-my-zsh/themes/
# An empty array have no effect
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git git-flow gitignore jira git-extras mvn osx sublime sudo jira
)

source $ZSH/oh-my-zsh.sh

# User configuration



HISTFILE=~/.histfile
HISTSIZE=100000
SAVEHIST=100000
bindkey -e
bindkey ^f  history-incremental-search-backward

  case $TERM in
  (xterm*)
        function precmd () { print -Pn "\e]0;%n($(id -ng))@%m:%~\a" }
  ;;
  esac

# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/Users/lperez/.zshrc'

autoload -Uz compinit
compinit
autoload promptinit
promptinit
#prompt adam1
prompt clint
#prompt phil
setopt correctall
setopt autocd
setopt auto_cd
setopt auto_pushd
setopt pushd_ignore_dups
setopt pushd_silent

#export JAVA_HOME=~/.sdkman/candidates/java/current
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home
export GROOVY_HOME=/Users/lperez/Desktop/work/groovy-2.4.11
export JDK_HOME=$JAVA_HOME
export M2_REPO=/Users/lperez/.m2/repository
export M2_HOME=/Users/lperez/Desktop/work/apache-maven-3.2.5
export M2_HOME=/Users/lperez/Desktop/work/apache-maven-3.5.4
alias ssvn='~/SVN'
alias ggit='~/Desktop/work/git'
alias wk='~/Desktop/work'
alias grostas='sudo du -a /data | sort -n -r | head -n 10'
alias apa7='sudo /Applications/XAMPP/bin/httpd -X'
alias apa5='sudo /Applications/XAMPP5538/bin/httpd -X'
git config --global user.name "lperez"
git config --global user.email "laurent.perez@sequoiasoft.com"
git config --global rebase.autosquash true
git config --global rerere.enabled true
git config --global pull.rebase preserve
git config --global remote.origin.prune true
git config --global alias.dog "log --all --decorate --oneline --graph"
git config --global alias.merge "merge -Xignore-all-space"
git config --global alias.tidy "rebase -i @{upstream}" 
git config --global alias.st status
git config --global alias.com commit
git config --global alias.ci commit
git config --global alias.br branch
git config --global alias.co checkout
git config --global alias.cl checkout
git config --global alias.superlog "log -p -M --follow --stat --"
alias atom='atom --disable-gpu'
alias glog='git lg1'
alias gk='gitk'
alias pull='git pull'
alias dev='git checkout develop'
alias lop='git checkout develop'
alias gwl='git worktree list'
alias gba='git branch -avv'
alias gco='git checkout'
alias gmm='git merge master'
alias gdo='git diff origin/master'
alias gdp='git diff @{push}..'
alias glp='git log @{push}..'
alias gpdo='git diff origin/master'
alias grso='git remote show origin'
alias co='git checkout'
alias grh='git reset --hard HEAD^'
alias itg='git co integration'
alias master='git co master'
alias ms='git checkout master'
alias mcc='mvn clean compile'
alias mcp='mvn clean package'
alias mci='mvn clean install'
alias mcu='mvn clean install -U'
alias mcd='mvn clean install deploy -U'
alias mi='mvn install'
alias mc='mvn compile'
alias mp='mvn package'
alias md='mvn deploy'
alias mt='mvn test'
alias mct='mvn clean test'
alias CLEARREPO='rm -fr ~/.m2/repository'
alias repoclear='rm -fr ~/.m2/repository'
alias sup='svn up'
alias ll='ls -la'
alias grep='egrep --exclude-dir=\.svn --color=auto'
alias s='cd ..'
alias c='clear'
alias ll='ls -la'
alias rtl='ls -rtla'
alias less='less --quiet'
alias '..'='cd ..'
alias -g ...='../..'
alias -g ....='../../..'
alias -g .....='../../../..'
alias svndiff='svn diff --diff-cmd ~/.diffwrap.sh'
alias sd='svn diff --diff-cmd=colordiff'
alias ant='ant -logger org.apache.tools.ant.listener.AnsiColorLogger'
alias eclipse='/Users/admin/work/eclipse/eclipse'
# servers
alias tbbweb1='ssh tbbweb1'
alias bbweb1='ssh bbweb1'
export REPO_GIT="/Users/lperez/Desktop/work/git"
PATH=/opt/local/bin:$PATH:$REPO_GIT # Add RVM to PATH for scripting

export NVM_DIR="/Users/admin/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

export PATH=/opt/local/bin:$PATH:$M2_HOME/bin:$GROOVY_HOME/bin

export PATH=$PATH:/usr/local/Cellar/php@7.2/7.2.21/bin

alias php="/usr/local/Cellar/php@7.2/7.2.21/bin/php"

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"




#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/lperez/.sdkman"
[[ -s "/Users/lperez/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/lperez/.sdkman/bin/sdkman-init.sh"
