version: '3.3'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
        - "./docker-web/www:/usr/share/nginx/html:ro"
        - "./docker-web/log:/var/log/nginx"
        - "./docker-web/nginx.conf:/etc/nginx/nginx.conf:ro"
    command: [nginx-debug, '-g', 'daemon off;']
    tty: true
    ports:
        - "127.0.0.1:80:80"
  php-fpm:
    image: php:fpm-alpine
    container_name: php-fpm
    volumes:
        - "./docker-web/www:/script:ro"
    ports:
        - "9000:9000"
    tty: true
